version: "3.9"

services:
  bot:
    build: .
    privileged: true  # ← дає доступ до всіх системних викликів
    network_mode: host
    pid: host
    container_name: ai-devops-bot
    restart: unless-stopped

    volumes:
      - /:/host
      
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      # Додаємо доступ до системних шин для reboot через systemctl
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

    command: npm run dev

    env_file:
      - .env

    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: ai-devops-redis
    restart: unless-stopped